### ISSUE TITLE
Progress Tracking Input

### ISSUE THREAD

**Issue by ndylanl** [ndylanl/MacroADATeam04Afternoon#1]
- [x] 1. Button in dashboard to this view
- [x] 2. camera to take 6 photos with head outline
- [x] 3. each photo will update the progress bar
- [x] 4. Result page; display photos

COA: usable camera when the button pressed, head outline appears and has the right shape and size, saves data in local, display from local

![Image](https://github.com/user-attachments/assets/8fb1dfb2-935f-48c7-9e35-3dd06bf41d87)

**Comment by geraldchester** [comment]
old one checked. please proceed to create backlog about the new revised version of progress tracking inputs.
