### ISSUE TITLE
Personal Health Activities Tracker

### ISSUE THREAD

**Issue by ndylanl** [ndylanl/MacroADATeam04Afternoon#3]
- [x] 1. personal health data can be retrieved from healthkit
- [x] 2. data is stored in app and analyzed throughout a week
- [x] 3. average score of sleep time, movement, stress level is displayed properly in the dashboard and weekly report

COA: data retrieved, stored, and displayed correctly
